export const SWITCH_MAIN_TAB = 'SWITCH_MAIN_TAB';

//HOME ACTION TYPES
export const START_SEARCH_DEVICE = 'START_SEARCH_DEVICE';
export const STOP_SEARCH_DEVICE = 'STOP_SEARCH_DEVICE';
export const UPDATE_DEVICE_LIST = 'UPDATE_DEVICE_LIST';
export const START_DEVICE_CONNECT = 'START_DEVICE_CONNECT';
export const SUCCESS_DEVICE_CONNECT = 'SUCCESS_DEVICE_CONNECT';
export const FAIL_DEVICE_CONNECT = 'FAIL_DEVICE_CONNECT';

//DEVICE ACTION TYPE
export const DEVICE_DISCONNECT = 'DEVICE_DISCONNECT';
export const START_READ_VERSION = 'START_READ_VERSION';
export const READ_VERSION = 'READ_VERSION';
export const START_READ_INSOLE_DATA = 'START_READ_INSOLE_DATA';
export const STOP_READ_INSOLE_DATA = 'STOP_READ_INSOLE_DATA';
export const READ_INSOLE_DATA = 'READ_INSOLE_DATA';
export const START_READ_VOLTAGE = 'START_READ_VOLTAGE';
export const READ_VOLTAGE = 'READ_VOLTAGE';
export const START_READ_BATCH = 'START_READ_BATCH';
export const READ_BATCH = 'READ_BATCH';
export const START_READ_STEP = 'START_READ_STEP';
export const READ_STEP = 'READ_STEP';

